def create_user_data_collection(db,collection_name):
    result = db.create_collection(collection_name, validator={
        '$jsonSchema': {
            'bsonType': 'object',
            'additionalProperties': False,
            'required': ['first_name','email','mobile_number', 'user_type'],
            'properties': {
                '_id': {
                    'bsonType': 'objectId',
                    'description': 'Unique identifier for the document, required and auto-generated by MongoDB'
                },
                'first_name': {
                    'bsonType': 'string',
                    'description': 'First name of the user, required and max length 50'
                },
                'last_name': {
                    'bsonType': 'string',
                    'description': 'Last name of the user, required and max length 50'
                },
                'email': {
                    'bsonType': 'string',
                    'description': 'Email of the user, required and unique'
                },
                'mobile_number': {
                    'bsonType': 'string',
                    'description': 'Mobile number of the user, required and unique'
                },
                'user_type': {
                    'bsonType': 'string',
                    'description': 'Type of the user, required and can be either "admin" or "customer"'
                },
                'session_token': {
                    'bsonType': 'string',
                    'description': 'Session token for the user'
                },
                'last_session_token_time': {
                    'bsonType': 'date',
                    'description': 'Timestamp when the last session token was created'
                }
            }
        }
    })
    print(f"Result: {result}")